/**********************************************************
 * This file is generated by 20-sim ANSI-C Code Generator
 *
 *  file:  common\MotionProfiles.cpp
 *  subm:  LoopController
 *  model: LoopController
 *  expmt: RELbotSimple
 *  date:  April 9, 2024
 *  time:  1:20:47 PM
 *  user:  Universiteit Twente
 *  from:  -
 *  build: 5.0.3.12565
 **********************************************************/

/* This file implements the functions necessary for motion profiles
   functions
*/


